### ISSUE TITLE
3dsMax for files (*.max) scene view needed 

### ISSUE THREAD

**Issue by kolindes** [WARP-LAB/files_3dmodelviewer#10]
Support for 3dsMax scenes would be perfect, specifically files with the extension *.max -- this would be incredibly convenient. If possible, it would be amazing to store the project folder on a Nextcloud server and have the ability to view the scene simultaneously.

**Comment by kroko** [comment]
Unless there is an open source JS and/or WASM implementation to read proprietary 3ds Max file format and convert it on the fly to something that can be serialised (eventually to Threejs structures) this wish unfortunately cannot not be fulfilled. 

My opinion is so pessimistic about such possibility that I will close this issue. Feel free to comment, this ticket can be reopened any time Autodesk wishes to open 3ds Max (or somebody wishes to reverse engineer it) :)
