### ISSUE TITLE
Support for Nextcloud 27

### ISSUE THREAD

**Issue by ThaDaVos** [WARP-LAB/files_3dmodelviewer#14]
## Is your feature request related to a problem? Please describe

When can we expect support for Nextcloud 27?
## Describe the solution you'd like

Support for Nextcloud 27
## Describe alternatives you've considered
None - as far as I know there are not alternative apps

**Comment by kroko** [comment]
v0.0.10 pushed <https://apps.nextcloud.com/apps/files_3dmodelviewer>
