### ISSUE TITLE
Update to NextCloud 27.0.1 failed with Viewer 0.0.11

### ISSUE THREAD

**Issue by NBDes** [WARP-LAB/files_3dmodelviewer#16]
Viewer 0.0.11 was running without problems on NC 26 but after updating to NC 27.0.1 the following error occurred:

[files_3dmodelviewer] Fatal: TypeError: OCP\AppFramework\App::__construct(): Argument #1 ($appName) must be of type string, null given, called in /var/www/html/custom_apps/files_3dmodelviewer/lib/AppInfo/Application.php on line 37 at <<closure>>

 0. /var/www/html/custom_apps/files_3dmodelviewer/lib/AppInfo/Application.php line 37
    OCP\AppFramework\App->__construct(null)
 1. /var/www/html/lib/private/ServerContainer.php line 107
    OCA\Files3dModelViewer\AppInfo\Application->__construct()
 2. /var/www/html/lib/private/ServerContainer.php line 186
    OC\ServerContainer->getAppContainer("files3dmodelviewer", "Files3dModelViewer")
 3. /var/www/html/lib/private/ServerContainer.php line 153
    OC\ServerContainer->getAppContainerForService("OCA\\Files3dMod ... n")
 4. /var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php line 133
    OC\ServerContainer->query("OCA\\Files3dMod ... n")
 5. /var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php line 94
    OC\AppFramework\Bootstrap\Coordinator->registerApps(["files_3dmodelviewer"])
 6. /var/www/html/lib/private/Installer.php line 143
    OC\AppFramework\Bootstrap\Coordinator->runLazyRegistration("files_3dmodelviewer")
 7. /var/www/html/apps/settings/lib/Controller/AppSettingsController.php line 451
    OC\Installer->installApp("files_3dmodelviewer")
 8. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 230
    OCA\Settings\Controller\AppSettingsController->enableApps(["files_3dmodelviewer"], [])
 9. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController(["OCA\\Settings\ ... "], "enableApps")
10. /var/www/html/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch(["OCA\\Settings\ ... "], "enableApps")
11. /var/www/html/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main("OCA\\Settings\\ ... r", "enableApps", ["OC\\AppFramewo ... "], ["settings.AppSettings.enableApps"])
12. /var/www/html/lib/base.php line 1071
    OC\Route\Router->match("/settings/apps/enable")
13. /var/www/html/index.php line 36
    OC::handleRequest()

**Comment by kroko** [comment]
yes, everything worked. i just updatad 26 instance to latest (26.0.4), so smth has changed in API - I understand that maybe in major 26->27 stepup smth as serious as changes in constructor def happens, but it seems that it has happened in patch release, just wow. will investigate late tonight or tomorrow.

**Comment by kroko** [comment]
please see if 0.0.12 solves the issue (it should populate from app store in a few hours)

**Comment by NBDes** [comment]
Thank you very much. Everything is working as it should be!
