### ISSUE TITLE
App "files_3dmodelviewer" cannot be installed because appinfo file cannot be read.

### ISSUE THREAD

**Issue by ZYQiang** [WARP-LAB/files_3dmodelviewer#18]
![企业微信截图_16982133013213](https://github.com/WARP-LAB/files_3dmodelviewer/assets/21325933/adfaa6b3-687c-4137-855f-191a101d5c18)
## Describe the bug
When clicked on to enable, this situation will occur.

**Comment by kroko** [comment]
please edit your ticket by filling out the full [bugreport template](https://github.com/WARP-LAB/files_3dmodelviewer/issues/new?assignees=&labels=bug%2C+0.+Needs+triage&projects=&template=bug_report.md&title=)

**Comment by kroko** [comment]
closing as no info was given
