### ISSUE TITLE
Not an issue, but large over 100 M files?

### ISSUE THREAD

**Issue by matti-owl** [WARP-LAB/files_3dmodelviewer#24]
Hello,

Thank you for excellent 3D viewer, just stunning! Is there anything that I could tweak on server side to make large models load and run? Thank you in advance!

Br Matti

**Comment by kroko** [comment]
everything is done on the client side (browser). internet connection needs to be decent, so that 100M+ files can be moved from server to your browser though.

**Comment by kroko** [comment]
on second thought - what format are the models? if they are ifc, rhino, step, iges, brep then JIT serialisation in javascript runtime within browser (uses https://github.com/ThatOpen/engine_web-ifc, https://github.com/mcneel/rhino3dm and https://github.com/kovacsv/occt-import-js) could be skipped if you converted them. that would affect loading time (parsing time) and overall mem usage, but not webgl rendering capabilities. it sounds unpractical for everyday usage though, but something to consider if you want to share batch of maaany laaarge files to i.e. your clients to browse through.
