### ISSUE TITLE
IFC not working on nextcloud 24.0.6

### ISSUE THREAD

**Issue by immomagic** [WARP-LAB/files_3dmodelviewer#5]
## Describe the bug

ifc fles, even small ones like 2MB, do not load. other formats do load but they take quite long. Im connected via LAN directly to the server where our nextcloud instance is running

## To Reproduce

Take a ifc file and try to look at it in the 3DModel Viewer

## Expected behavior

The ifc file should load an

## I have checked that the files are not corrupted

Yes, using `BIM VISION`.

## Browser log

```
ConsoleLogger.js:33 [INFO] viewer: Opening viewer for file  {app: 'viewer', uid: 'm.burgert', path: '/BKK Cloud/AVA/haus.ifc'}
ConsoleLogger.js:29 [DEBUG] viewer: Fetching additional files... {app: 'viewer', uid: 'm.burgert'}
web-ifc-api-browser.js:1 
        
       Uncaught (in promise) EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at new Function (<anonymous>)
    at createNamedFunction (web-ifc-api-browser.js:1:213972)
    at extendError (web-ifc-api-browser.js:1:214156)
    at WebIFCWasm2 (web-ifc-api-browser.js:1:243576)
    at IfcAPI2.<anonymous> (web-ifc-api-browser.js:1:1379921)
    at Generator.next (<anonymous>)
    at web-ifc-api-browser.js:1:1162
    at new Promise (<anonymous>)
    at __async (web-ifc-api-browser.js:1:849)
    at IfcAPI2.Init (web-ifc-api-browser.js:1:1379712)
createNamedFunction @ web-ifc-api-browser.js:1
extendError @ web-ifc-api-browser.js:1
WebIFCWasm2 @ web-ifc-api-browser.js:1
(anonym) @ web-ifc-api-browser.js:1
(anonym) @ web-ifc-api-browser.js:1
__async @ web-ifc-api-browser.js:1
Init @ web-ifc-api-browser.js:1
(anonym) @ files_3dmodelviewer.js?v=570800e1-40:1
Promise.then (asynchron)
(anonym) @ files_3dmodelviewer.js?v=570800e1-40:1
Promise.then (asynchron)
ImportContent @ files_3dmodelviewer.js?v=570800e1-40:1
Import @ files_3dmodelviewer.js?v=570800e1-40:1
ImportLoadedMainFile @ files_3dmodelviewer.js?v=570800e1-40:1
ImportLoadedFiles @ files_3dmodelviewer.js?v=570800e1-40:1
(anonym) @ files_3dmodelviewer.js?v=570800e1-40:1
DecompressArchives @ files_3dmodelviewer.js?v=570800e1-40:1
(anonym) @ files_3dmodelviewer.js?v=570800e1-40:1
(anonym) @ files_3dmodelviewer.js?v=570800e1-40:1
setTimeout (asynchron)
RunTaskAsync @ files_3dmodelviewer.js?v=570800e1-40:1
onReady @ files_3dmodelviewer.js?v=570800e1-40:1
TaskReady @ files_3dmodelviewer.js?v=570800e1-40:1
(anonym) @ files_3dmodelviewer.js?v=570800e1-40:1
Promise.finally (asynchron)
GetFileContent @ files_3dmodelviewer.js?v=570800e1-40:1
runTask @ files_3dmodelviewer.js?v=570800e1-40:1
(anonym) @ files_3dmodelviewer.js?v=570800e1-40:1
setTimeout (asynchron)
RunOnce @ files_3dmodelviewer.js?v=570800e1-40:1
Run @ files_3dmodelviewer.js?v=570800e1-40:1
(anonym) @ files_3dmodelviewer.js?v=570800e1-40:1
GetContent @ files_3dmodelviewer.js?v=570800e1-40:1
LoadFiles @ files_3dmodelviewer.js?v=570800e1-40:1
ImportFiles @ files_3dmodelviewer.js?v=570800e1-40:1
LoadModel @ files_3dmodelviewer.js?v=570800e1-40:1
LoadModelFromInputFiles @ files_3dmodelviewer.js?v=570800e1-40:1
LoadModelFromFileList @ files_3dmodelviewer.js?v=570800e1-40:1
Init3DViewerFromFileList @ files_3dmodelviewer.js?v=570800e1-40:1
(anonym) @ files_3dmodelviewer.js?v=570800e1-40:1
tryCatch @ files_3dmodelviewer.js?v=570800e1-40:1
(anonym) @ files_3dmodelviewer.js?v=570800e1-40:1
(anonym) @ files_3dmodelviewer.js?v=570800e1-40:1
Appvue_type_script_lang_js_asyncGeneratorStep @ files_3dmodelviewer.js?v=570800e1-40:1
_next @ files_3dmodelviewer.js?v=570800e1-40:1
Promise.then (asynchron)
Appvue_type_script_lang_js_asyncGeneratorStep @ files_3dmodelviewer.js?v=570800e1-40:1
_next @ files_3dmodelviewer.js?v=570800e1-40:1
(anonym) @ files_3dmodelviewer.js?v=570800e1-40:1
(anonym) @ files_3dmodelviewer.js?v=570800e1-40:1
construct @ files_3dmodelviewer.js?v=570800e1-40:1
(anonym) @ files_3dmodelviewer.js?v=570800e1-40:1
(anonym) @ vue.runtime.esm.js:1989
et @ vue.runtime.esm.js:1915
Promise.then (asynchron)
Ke @ vue.runtime.esm.js:1942
at @ vue.runtime.esm.js:1999
e.$nextTick @ vue.runtime.esm.js:3542
mounted @ files_3dmodelviewer.js?v=570800e1-40:1
We @ vue.runtime.esm.js:1863
ln @ vue.runtime.esm.js:4235
insert @ vue.runtime.esm.js:3158
_ @ vue.runtime.esm.js:6390
bo.nodeOps @ vue.runtime.esm.js:6609
e._update @ vue.runtime.esm.js:3963
r @ vue.runtime.esm.js:4081
bn.get @ vue.runtime.esm.js:4495
bn.run @ vue.runtime.esm.js:4570
yn @ vue.runtime.esm.js:4326
(anonym) @ vue.runtime.esm.js:1989
et @ vue.runtime.esm.js:1915
Promise.then (asynchron)
Ke @ vue.runtime.esm.js:1942
at @ vue.runtime.esm.js:1999
(anonym) @ vue.runtime.esm.js:4418
bn.update @ vue.runtime.esm.js:4560
de.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
Cn.set @ vue.runtime.esm.js:4644
(anonym) @ Viewer.vue:431
u @ runtime.js:63
(anonym) @ runtime.js:294
(anonym) @ runtime.js:119
Vm @ Download.vue?b226:19
i @ Download.vue?b226:19
Promise.then (asynchron)
Vm @ Download.vue?b226:19
i @ Download.vue?b226:19
Promise.then (asynchron)
Vm @ Download.vue?b226:19
i @ Download.vue?b226:19
(anonym) @ Download.vue?b226:19
(anonym) @ Download.vue?b226:19
openFile @ Viewer.vue:345
file @ Viewer.vue:256
We @ vue.runtime.esm.js:1863
bn.run @ vue.runtime.esm.js:4584
yn @ vue.runtime.esm.js:4326
(anonym) @ vue.runtime.esm.js:1989
et @ vue.runtime.esm.js:1915
Promise.then (asynchron)
Ke @ vue.runtime.esm.js:1942
at @ vue.runtime.esm.js:1999
(anonym) @ vue.runtime.esm.js:4418
bn.update @ vue.runtime.esm.js:4560
de.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
value @ Viewer.js:193
gm @ FilesActionHandler.js:40
action @ merged-index.js?v=570800e1-40:3025
_onClickFile @ merged-index.js?v=570800e1-40:4986
be @ _executeBound.js:8
(anonym) @ bind.js:10
(anonym) @ restArguments.js:16
dispatch @ jquery.js:5430
m.handle @ jquery.js:5234
App.vue:323 No new notification data received
App.vue:355 Polling interval updated to 30000
```

<details>
<summary>How to access your browser console (Click to expand)</summary>

### Chrome

1. Press either CTRL + SHIFT + I / CMD + ALT + I or F12 to open the Developer Tools.
2. Click the “console” tab.

### Safari

1. Press CMD + ALT + I to open the Web Inspector.
2. See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

### IE

1. Press F12 to open the developer tools.
2. Click the “console” tab.

### Firefox

1. Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
2. or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

### Opera

1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.

</details>

### How the app was installed?

- Via app store.

### App server configuration Parameters

- `apps_path` parameter is not explicitly configured/customised in `config/config.php`

### Nextcloud

- Version: 24.0.6
- Webserver: apache

### Desktop

- OS: Windows 11
- Browser and version: Edge 110.0.1587.57

### Handheld

- Device: 
- OS: 
- Browser and version: 

## Additional context
The IFC test files I used:
[ifcs.zip](https://github.com/WARP-LAB/files_3dmodelviewer/files/10883676/ifcs.zip)

**Enabled:
  - activity: 2.16.0
  - admin_audit: 1.14.0
  - cloud_federation_api: 1.7.0
  - dav: 1.22.0
  - email_template_example: 0.0.1
  - external: 4.0.1
  - federatedfilesharing: 1.14.0
  - files: 1.19.0
  - files_3dmodelviewer: 0.0.6
  - files_accesscontrol: 1.14.1
  - files_automatedtagging: 1.14.1
  - files_downloadactivity: 1.15.0
  - files_external: 1.16.1
  - files_linkeditor: 1.1.13
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_scripts: 2.0.3
  - files_sharing: 1.16.2
  - files_snapshots: 1.0.5
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - guests: 2.3.0
  - impersonate: 1.11.1
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - notifications: 2.12.1
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - provisioning_api: 1.14.0
  - settings: 1.6.0
  - sharepoint: 1.12.0
  - side_menu: 2.5.2
  - systemtags: 1.14.0
  - theming: 1.15.0
  - theming_customcss: 1.12.0
  - twofactor_backupcodes: 1.13.0
  - unroundedcorners: 1.0.3
  - updatenotification: 1.14.0
  - viewer: 1.8.0
  - workflowengine: 2.6.0**
 
_Disabled:
  - accessibility: 1.8.0
  - announcementcenter: 6.3.1
  - circles: 24.0.0
  - comments: 1.12.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - encryption
  - federation: 1.12.0
  - files_fulltextsearch: 24.0.1
  - files_fulltextsearch_tesseract: 24.0.0
  - files_photospheres: 1.24.3
  - files_trackdownloads: 1.11.0
  - files_trashbin: 1.12.0
  - firstrunwizard: 2.11.0
  - fulltextsearch: 23.0.0
  - nextcloud_announcements: 1.11.0
  - privacy: 1.6.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - sharebymail: 1.12.0
  - sharelisting: 1.1.1
  - support: 1.5.0
  - survey_client: 1.10.0
  - text: 3.5.1
  - transfer: 0.6.0
  - user_ldap
  - user_status: 1.2.0
  - weather_status: 1.2.0_

**Comment by kroko** [comment]
Perfect bug report ❤️ 

Yeah, it is related to [this line](https://github.com/WARP-LAB/files_3dmodelviewer/blob/main/lib/Listener/AddCspEventListener.php#L21) where this app informs NC that we want 'unsafe-eval' to be true and thus your error would not happen

> Uncaught (in promise) EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

but it is affected what and how CSP policies other apps load. I quite haven't yet figured out how CSP works in NC yet, till then drastic fix incoming.

**Comment by kroko** [comment]
Please try version 0.0.7 and report back. Just uploaded the new version in NC app store, it will take a bit time to propagate.

**Comment by kroko** [comment]
@immomagic ping

**Comment by immomagic** [comment]
Sorry, it is not working on our nextcloud instance 24 - on 25 it works with a bit latency.


Für eventuelle Fragen stehe ich Ihnen jederzeit gern zur Verfügung und verbleibe


mit freundlichen Grüßen

gez. M.A. Martin Burgert


IMMO-MAGIC GmbH
D-99084 Erfurt, Pergamentergasse 9

D-99084 Erfurt, Augustinerstrasse 27


Tel.: +49 (361) 60250-117
Mobil: +49 (151) 58253-117
Fax: +49 (361) 60250-20
Mail: ***@***.***
Web: www.immo-magic.de<http://www.immo-magic.de/>

________________________________
Von: kroko ***@***.***>
Gesendet: Friday, March 24, 2023 4:38:33 PM
An: WARP-LAB/files_3dmodelviewer ***@***.***>
Cc: immomagic ***@***.***>; Mention ***@***.***>
Betreff: Re: [WARP-LAB/files_3dmodelviewer] IFC not working on nextcloud 24.0.6 (Issue #5)


@immomagic<https://github.com/immomagic> ping

**Comment by kroko** [comment]
> Sorry, it is not working on our nextcloud instance 24

Unfortunately I will not try to make it work in 24 as [it will bee EOL 2023-05 (in 2 months) anyways](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule)

> on 25 it works with a bit latency

Expected. IFC is _decoded_ on the fly using JS + WASM [web-ifc](https://github.com/IFCjs/web-ifc) and that takes time. On _desktop_ duration of double clicking IFC file and BIM VISION showing the contents is not instant, too, isn't it 😉, in browser it will take longer.
