### ISSUE TITLE
Poor performance on large files

### ISSUE THREAD

**Issue by ershovdz** [WARP-LAB/files_3dmodelviewer#8]
Poor performance when open the attached obj file.
Opening file takes too much time and memory. But if I open the same file in https://3dviewer.net/# it opens very fast.
[Penthouse.zip](https://github.com/WARP-LAB/files_3dmodelviewer/files/11061204/Penthouse.zip)

**Comment by kroko** [comment]
Confirmed.

**Comment by ershovdz** [comment]
Just to make it clear.
My configuration: Windows 11 22H2, Nvidia 3060, 32 Gb Ram, CPU Amd Ryzen 5800H.
I use this url to open in browsers for 3dviewer: 
https://3dviewer.net/#model=https://bucket.cdn-d01.warp.lv/user-ershovdz/Penthouse-org.obj
Clear cache in browsers. Open url.
Chrome (latest version): 10 seconds and 900 Mb ram
Firefox (latest version): 15 seconds and 800 Mb ram

I use this url for nextcloud app files3dmodel viewer for the same file: 
http://localhost:8080/apps/files/?dir=/&openfile=4893 
Clear cache in browsers. Open url.
Chrome (latest version): 19 seconds and 3000 Mb ram
Firefox (latest version): didn't wait for opening (more 90 seconds) and it took 5000 Mb of ram

**Comment by ershovdz** [comment]
Looks like I've found the root cause. Just remove this line:
https://github.com/WARP-LAB/files_3dmodelviewer/blob/36acc7ec304123c4378ccc47d09b32516ea29627/src/js/App/App.mjs#L58 
It's disable vue reactivity for viewer.

**Comment by kroko** [comment]
note to myself: @AbsolutePhoenix in https://github.com/WARP-LAB/files_3dmodelviewer/issues/12 has found that it happens above 16MB mark for STL files.

**Comment by kroko** [comment]
@ershovdz please try 0.0.11 with your [Penthouse.zip](https://github.com/WARP-LAB/files_3dmodelviewer/files/11061204/Penthouse.zip)

**Comment by kroko** [comment]
if the issue persists, please report and i will reopen this ticket.
